name: build-and-publish
run-name: Build binaries and publish new release

on: 
  push:
    tags:
      - v**

jobs:
  build-and-publish:
    name: Build binaries and publish new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Build 'rates' module
        run: go build -C rates -o ../bin/
      - name: Build 'bigquery' module
        run: go build -C bigquery -o ../bin/
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            bin/rates
            bin/bigquery
    
